// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkInepDgRMnKZ8i9zoyqGpJXpoY-avWAM',
    appId: '1:135394737616:web:e62d43ce7c8d1667670dd5',
    messagingSenderId: '135394737616',
    projectId: 'newsapp-dde18',
    authDomain: 'newsapp-dde18.firebaseapp.com',
    storageBucket: 'newsapp-dde18.firebasestorage.app',
    measurementId: 'G-DD7SL46WVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWlOvFfZJOnb9sIh56TQpWbxF9xlNzbRQ',
    appId: '1:135394737616:android:b93663a8c73bfddf670dd5',
    messagingSenderId: '135394737616',
    projectId: 'newsapp-dde18',
    storageBucket: 'newsapp-dde18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfG5HgNlfHnW7XK9TmZWzxlSuNVZqADhA',
    appId: '1:135394737616:ios:c417b9464e483d55670dd5',
    messagingSenderId: '135394737616',
    projectId: 'newsapp-dde18',
    storageBucket: 'newsapp-dde18.firebasestorage.app',
    iosClientId: '135394737616-j3531iivb1n0iq4cldiuc9qvand4e44m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNewsApp',
  );
}
